name: mindbox_ios
description: The implementation of 'mindbox' plugin for the iOS platform.
version: 2.1.3
homepage: https://mindbox.cloud/
repository: https://github.com/mindbox-moscow/flutter-sdk/tree/master/mindbox_ios

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: mindbox
    platforms:
      ios:
        pluginClass: MindboxIosPlugin

dependencies:
  flutter:
    sdk: flutter
  mindbox_platform_interface:
    git:
      url: https://github.com/AurelVU/flutter-sdk.git
      path: mindbox_platform_interface
      ref: inapp_flutter_support

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
