name: mindbox
description: Flutter Mindbox SDK. Plugin wrapper over of Mindbox iOS/Android SDK.
version: 2.3.0
homepage: https://mindbox.cloud/
repository: https://github.com/mindbox-moscow/flutter-sdk/tree/master/mindbox

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: mindbox_android
      ios:
        default_package: mindbox_ios

dependencies:
  flutter:
    sdk: flutter
  mindbox_android:
    git:
      url: https://github.com/AurelVU/flutter-sdk.git
      path: mindbox_android
      ref: inapp_flutter_support
  mindbox_ios:
    git:
      url: https://github.com/AurelVU/flutter-sdk.git
      path: mindbox_ios
      ref: inapp_flutter_support
  mindbox_platform_interface:
    git:
      url: https://github.com/AurelVU/flutter-sdk.git
      path: mindbox_platform_interface
      ref: inapp_flutter_support

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
